### ISSUE TITLE
api.request_token(code) returns Bad Request

### ISSUE THREAD

**Issue by eombucket** [ossobv/exactonline#13]
```
from exactonline.api import ExactApi
from exactonline.exceptions import ObjectDoesNotExist
from exactonline.storage import IniStorage

class MyIniStorage(IniStorage):
    def __init__(self, filename_or_fp, **kwargs):
        if kwargs.get('exact_base_url'):
            self.exact_base_url = kwargs.get('exact_base_url')
        if kwargs.get('exact_client_id'):
            self.exact_client_id = kwargs.get('exact_client_id')
        if kwargs.get('exact_client_secret'):
            self.exact_client_secret = kwargs.get('exact_client_secret')
        res = super(MyIniStorage, self).__init__(filename_or_fp)
        return res
    def get_response_url(self):
        "Configure your custom response URL."
        return self.get_base_url() + '/oauth/success/'
    def get_base_url(self):
        return self.exact_base_url
    def get_client_id(self):
        return self.exact_client_id
    def get_client_secret(self):
        return self.exact_client_secret
    def get_auth_url(self):
        return 'https://start.exactonline.com/api/oauth2/auth'
    def get_rest_url(self):
        return 'https://start.exactonline.com/api'
    def get_token_url(self):
        return 'https://start.exactonline.com/api/oauth2/token'

def get_api():
    exact_client_secret='BZcjZWtTytwt'
    exact_client_id='{bce89979-dfbd-4613-9c50-cb22e4615edf}'
    exact_base_url = 'http://localhost'
    indata = dict(
        exact_base_url=exact_base_url,
        exact_client_id=exact_client_id,
        exact_client_secret=exact_client_secret
    )
    storage = MyIniStorage('./config.ini',**indata)
    api = ExactApi(storage=storage)
    return api

api = get_api()

# url = api.create_auth_request_url()
# print url
code = "Z-F-%21IAAAAHcFmYuXjirm3BcAmUYqII6Tnq4oHgoFXfT97pLDZptHAQEAAAHLmDexFg221zax0Rp2vXOzcviTsNbowNi6K7PEOMkC6XbRJpeb23fmFrUl_pjVsfATJuFx96AjA-vs3TspQpdz1oiNZ4J_1NHILwEZf9fgyqZwu74DqU-V07ahrznZHHwrqyoWMdLDMRn7kqsuqGEg3RpR2H5QPw8maQAA-7JTCplTeSUbsx2V3r3TUDe6SjfIFgUfn95HCXbd7LvnrlkWUZt8oqbupIPU36guapJbDGtOKJXJTAMCn24TRAEfIewE4vXElLcmC3DcxA48Tx12gUV4cRxSQHAozQfWqjvmF3r7NtLTyvNlkgneKF3uGhpTed1caB-0r3_1uBW7OcuW"
print api.request_token(code)
```

i am getting 
```
exactonline.http.HTTPError: HTTPError: """400 Bad Request
Content-Type: text/html
Content-Length: 11

Bad Request"""
```

**Comment by wdoekes** [comment]
That's exactly 0 questions.

What I can tell you:
- client_id needs the surrounding braces (`{` and `}`)
- exactonline likes the base_url to match the url it has stored in its config
- exactonline may refuse localhost as base_url
- there is a `%21` in that code which you did not unescape before feeding it to request_token. that should probably be a `!`

**Comment by wdoekes** [comment]
And over here I get this, which is a lot more informative:
```
Traceback (most recent call last):
  File "<stdin>", line 45, in <module>
  File "/srv/virtualenvs/bosso/src/exactonline/exactonline/rawapi.py", line 69, in request_token
    response = _json_safe(http_post(url, token_data, opt=opt_secure))
  File "/srv/virtualenvs/bosso/src/exactonline/exactonline/http.py", line 254, in http_post
    return _http_request(url, method='POST', data=_marshalled(data), opt=opt)
  File "/srv/virtualenvs/bosso/src/exactonline/exactonline/http.py", line 327, in _http_request
    data)
exactonline.http.HTTPError: HTTPError: Bad Request
-----------------------------------------------------------------------
POST https://start.exactonline.com/api/oauth2/token
Content-Length: 565

client_id=%7Bbce89979-dfbd-4613-9c50-cb22e4615edf%7D&client_secret=BZcjZWtTytwt&code=Z-F-%21IAAAAHcFmYuXjirm3BcAmUYqII6Tnq4oHgoFXfT97pLDZptHAQEAAAHLmDexFg221zax0Rp2vXOzcviTsNbowNi6K7PEOMkC6XbRJpeb23fmFrUl_pjVsfATJuFx96AjA-vs3TspQpdz1oiNZ4J_1NHILwEZf9fgyqZwu74DqU-V07ahrznZHHwrqyoWMdLDMRn7kqsuqGEg3RpR2H5QPw8maQAA-7JTCplTeSUbsx2V3r3TUDe6SjfIFgUfn95HCXbd7LvnrlkWUZt8oqbupIPU36guapJbDGtOKJXJTAMCn24TRAEfIewE4vXElLcmC3DcxA48Tx12gUV4cRxSQHAozQfWqjvmF3r7NtLTyvNlkgneKF3uGhpTed1caB-0r3_1uBW7OcuW&grant_type=authorization_code&redirect_uri=http%3A//localhost/oauth/success/
-----------------------------------------------------------------------
<RESP> 400 Bad Request
Content-Type: text/html
Content-Length: 11

Bad Request
-----------------------------------------------------------------------
```

**Comment by MartijnDevNull** [comment]
Same problem here

`Traceback (most recent call last):
  File "/home/martijn/Code/Exact/exact.py", line 15, in <module>
    api.request_token("[token]")
  File "/usr/lib/python3.6/site-packages/exactonline/rawapi.py", line 69, in request_token
    response = _json_safe(http_post(url, token_data, opt=opt_secure))
  File "/usr/lib/python3.6/site-packages/exactonline/http.py", line 254, in http_post
    return _http_request(url, method='POST', data=_marshalled(data), opt=opt)
  File "/usr/lib/python3.6/site-packages/exactonline/http.py", line 327, in _http_request
    data)
exactonline.http.HTTPError: HTTPError: Bad Request
-----------------------------------------------------------------------
POST https://start.exactonline.nl/api/oauth2/token
Content-Length: 567

client_id=[clientid]&client_secret=[key]&code=[code]&grant_type=authorization_code&redirect_uri=http%3A//exact.local/oauth/success/
-----------------------------------------------------------------------
<RESP> 400 Bad Request
Content-Type: text/html
Content-Length: 11

Bad Request
-----------------------------------------------------------------------`

**Comment by MartijnDevNull** [comment]
@eombucket @wdoekes for me accidentally leaving in the `api.request_token(code)` in the code was turning out to be the problem since it re-validates an old token.

**Comment by wdoekes** [comment]
Thanks for the feedback @MartijnDevNull.

Closing for lack of well-defined problem.
