### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by wpxgit** [ossobv/exactonline#5]
Is the Package python3 compatible?
I got the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/autorefresh.py", line 15, in rest
    decoded = super(Autorefresh, self).rest(method, resource, data=data)
  File "/usr/local/lib/python3.4/site-packages/exactonline/rawapi.py", line 104, in rest
    response = self._rest_query(method, url, data)
  File "/usr/local/lib/python3.4/site-packages/exactonline/rawapi.py", line 146, in _rest_query
    response = http_get(url, opt=(opt_secure | opt_custom))
  File "/usr/local/lib/python3.4/site-packages/exactonline/http.py", line 219, in http_get
    return _http_request(url, method='GET', opt=opt)
  File "/usr/local/lib/python3.4/site-packages/exactonline/http.py", line 300, in _http_request
    response
exactonline.http.HTTPError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exayt.py", line 10, in <module>
    invoice = api.invoices.get(invoice_number='16700002')
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/invoices.py", line 16, in get
    invoice_dict = super(Invoices, self).get(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/manager.py", line 63, in get
    ret = self.filter(top=2, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/invoices.py", line 46, in filter
    return super(Invoices, self).filter(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/manager.py", line 81, in filter
    ret = self._api.restv1('GET', self.resource + args)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/v1division.py", line 29, in restv1
    return self.rest(method, resource, data=data)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/unwrap.py", line 18, in rest
    decoded = super(Unwrap, self).rest(method, resource, data=data)
  File "/usr/local/lib/python3.4/site-packages/exactonline/api/autorefresh.py", line 21, in rest
    self.refresh_token()
  File "/usr/local/lib/python3.4/site-packages/exactonline/rawapi.py", line 83, in refresh_token
    response = http_post(url, refresh_data, opt=opt_secure)
  File "/usr/local/lib/python3.4/site-packages/exactonline/http.py", line 234, in http_post
    return _http_request(url, method='POST', data=data, opt=opt)
  File "/usr/local/lib/python3.4/site-packages/exactonline/http.py", line 254, in _http_request
    proto = url.split(':', 1)[0]
TypeError: 'str' does not support the buffer interface

**Comment by wdoekes** [comment]
I think this should fix it. Thanks for reporting!

**Comment by wpxgit** [comment]
Thanks, i will try it!
